version: '3.8'

services:
  helloworld:
      image: tutum/hello-world
      networks:
        services:
            aliases:
              - helloworld

networks:
  services:
    external: true
    name: services