version: '3.5'

services:

  reverse_proxy:
    container_name: reverse_proxy
    image: owasp/modsecurity-crs:nginx-alpine
    ports:
      - '80:80'
      - '443:443'
    env_file: ./reverse_proxy.env
    volumes:
      - ./conf.d/proxy.conf.template:/etc/nginx/templates/conf.d/proxy.conf.template
      - ./includes/ssl.conf.template:/etc/nginx/templates/includes/ssl.conf.template
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
   
      - /etc/letsencrypt/live/helloworld.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/helloworld.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    restart: always
    networks:
      reverse_proxy:
        aliases:
          - reverse_proxy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: 5

networks:
  reverse_proxy:
    external: true
