version: '3.5'

services:

  reverse_proxy:
    container_name: reverse_proxy
    image: owasp/modsecurity-crs:nginx-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - /etc/letsencrypt/live/helloworld.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/helloworld.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    environment:
      - PROXY=1
    restart: always
    networks:
      reverse_proxy:
        aliases:
          - reverse_proxy

networks:
  reverse_proxy:
    external: true
