version: '3.5'

services:
  reverse_proxy:
    container_name: reverse_proxy
    ports:
      - '80:80'
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    environment:
      - PROXY=1
    restart: always
    image: owasp/modsecurity-crs:nginx-alpine
    networks:
      reverse_proxy:
        aliases:
          - reverse_proxy
networks:
  reverse_proxy:
    external: true
