version: '3'

services:
  reverse_proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: reverse_proxy
    restart: always
    environment:
      DEFAULT_HOST: default.vhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-letsencrypt-companion:
    image  : nginxproxy/acme-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"