version: '3.5'

services:

  reverse_proxy:
    container_name: reverse_proxy
    image: owasp/modsecurity-crs:nginx-alpine
    ports:
      - '80:80'
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ../cert/helloworld.com:/etc/nginx/ssl/helloworld.com
    environment:
      - PROXY=1
    restart: always
    networks:
      reverse_proxy:
        aliases:
          - reverse_proxy

networks:
  reverse_proxy:
    external: true
